version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - sudo yum update -y && sudo yum install -y docker
      - docker --version || exit 1  # Check Docker version to confirm installation

      - echo Installing AWS CLI...
      - sudo yum install -y aws-cli
      - aws --version || exit 1  # Check AWS CLI version to confirm installation

      - echo Checking Docker service status...
      - sudo systemctl status docker || echo "Docker service may not be running."

  pre_build:
    commands:
      - echo Configuring AWS CLI...
      - aws configure set region us-east-1

      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 034362047502.dkr.ecr.us-east-1.amazonaws.com || exit 1
      - echo Build started on `date`

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t moiz/project simple-app/. || exit 1

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker tag moiz/project:latest 034362047502.dkr.ecr.us-east-1.amazonaws.com/moiz/project:latest
      - echo Checking images before push...
      - docker images || exit 1  # List images to confirm tagging
      - echo Pushing image...
      - |
        {
          docker push 034362047502.dkr.ecr.us-east-1.amazonaws.com/moiz/project:latest
        } || {
          echo "Docker push failed. Check the error above."
          exit 1
        }

artifacts:
  files:
    - '**/*'
