version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo apt-get update -y
      - sudo apt-get install -y unzip  # Install unzip if needed
      - docker --version || { echo "Docker is not installed"; exit 1; }
      - aws --version || { echo "AWS CLI is not installed"; exit 1; }

  pre_build:
    commands:
      - echo "Ensuring Docker is running..."
      - sudo systemctl start docker || true  # Start Docker if not running
      - docker info || { echo "Docker is not running properly"; exit 1; }

      - echo "Configuring AWS CLI..."
      - aws configure set region us-east-1

      - echo "Verifying ECR repository..."
      - aws ecr describe-repositories --repository-names moiz/project --region us-east-1 || { echo "ECR repository not found"; exit 1; }

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 034362047502.dkr.ecr.us-east-1.amazonaws.com || exit 1
      - echo "Build started on `date`"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t moiz/project simple-app/. || exit 1

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker tag moiz/project:latest 034362047502.dkr.ecr.us-east-1.amazonaws.com/moiz/project:latest
      - echo "Checking images before push..."
      - docker images || exit 1  # List images to confirm tagging
      - echo "Pushing image..."
      - |
        {
          docker push 034362047502.dkr.ecr.us-east-1.amazonaws.com/moiz/project:latest
        } || {
          echo "Docker push failed. Check the error above."
          exit 1
        }

artifacts:
  files:
    - '**/*'
