version: 0.2

phases:
  install:
    commands:
      - echo "Installing Docker..."
      - sudo apt-get update -y && sudo apt-get install -y docker.io
      - sleep 10  # Wait for Docker to start
      - docker --version || exit 1

      - echo "Installing unzip..."
      - sudo apt-get install -y unzip

      - echo "Installing AWS CLI v2..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo chmod +x ./aws/install  # Ensure the install script is executable
      - sudo ./aws/install || exit 1  # Ensure the install step exits if it fails
      - aws --version || exit 1  # Confirm successful installation of AWS CLI

      - echo "Cleaning up installation files..."
      - rm -rf awscliv2.zip aws

  pre_build:
    commands:
      - echo "Configuring AWS CLI..."
      - aws configure set region us-east-1

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 034362047502.dkr.ecr.us-east-1.amazonaws.com || exit 1
      - echo "Build started on `date`"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t moiz/project simple-app/. || exit 1

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker tag moiz/project:latest 034362047502.dkr.ecr.us-east-1.amazonaws.com/moiz/project:latest
      - echo "Checking images before push..."
      - docker images || exit 1  # List images to confirm tagging
      - echo "Pushing image..."
      - |
        {
          docker push 034362047502.dkr.ecr.us-east-1.amazonaws.com/moiz/project:latest
        } || {
          echo "Docker push failed. Check the error above."
          exit 1
        }

artifacts:
  files:
    - '**/*'
