version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - sudo yum update -y && sudo yum install -y docker
      - docker --version

      - echo Installing AWS CLI...
      # Install AWS CLI using package manager
      - sudo yum install -y aws-cli
      # Verify AWS CLI installation
      - aws --version

  pre_build:
    commands:
      - echo Configuring AWS CLI...
      # Set AWS region (adjust based on your region)
      - aws configure set region us-east-1

      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 034362047502.dkr.ecr.us-east-1.amazonaws.com
      - echo Build started on `date`

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t moiz/project simple-app/.

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker tag moiz/project:latest 034362047502.dkr.ecr.us-east-1.amazonaws.com/moiz/project:latest
      - docker push 034362047502.dkr.ecr.us-east-1.amazonaws.com/moiz/project:latest

artifacts:
  files:
    - '**/*'
