version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - yum update -y && yum install -y docker
      - docker --version
      - sudo service docker start
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 034362047502.dkr.ecr.us-east-1.amazonaws.com
      - echo Build started on `date`
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t moiz/project simple-app/.
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker tag moiz/project:latest 034362047502.dkr.ecr.us-east-1.amazonaws.com/moiz/project:latest
      - docker push 034362047502.dkr.ecr.us-east-1.amazonaws.com/moiz/project:latest
artifacts:
  files:
    - '**/*'
  discard-paths: yes
